
# Welcome to the DimensionSpawn config.
# Here you can set the dimension and the coordinates for player spawning and respawning.
[General]
	#Here you can enable and disable the usage of a safe spawnpoint.
	safeSpawn = true
	#Here you set the range of the safe spawn search.
	#Range: 0 ~ 10000
	safeSpawnRange = 10000

[Dimension]
	#Here you can enable and disable the usage of a dimension.
	useDimension = true
	# There you can define a default dimension to spawn. Syntax: modid:world_id. You can use '/execute in' tab-completion to find a list of available dimensions.
	dimension = "minecraft:the_end"

[Coordinates]
	#Here you can enable and disable the usage of a coordinates.
	useCoordinates = false
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	x = 0.0
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	y = 0.0
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	z = 0.0
	#Range: -180.0 ~ 180.0
	yaw = 0.0
	#Range: -90.0 ~ 90.0
	pitch = 0.0

